### PR TITLE
Delete comments

### PR DESCRIPTION
**Pull request by sgoraczynski**
https://github.com/sgoraczynski/canvas-helmet/issues/3
Don't You think, that deleting comments can make problems in the future developement of this project??

### CODE REVIEW

**Review by pbrudny — APPROVED** [review]
Well done.

**Comment by pbrudny** [comment]
@sgoraczynski Deleting comment is a good idea :) It will not cause any problems in the future

**Comment by pbrudny** [comment]
There is a conflict now. To solve that you will need to click Resolve conflicts - and choose the right code for the section.

Like here:
```
<<<<<<< refactor-3
            ctx.lineTo(132, 120);
=======
            ctx.lineTo(xCoordinate, 120);    								//Sides and upper helmet
>>>>>>> main
```

**Comment by sgoraczynski** [comment]
How to choose how to resolve the problem?

**Comment by sgoraczynski** [comment]
And what if there isn't proper one?

**Comment by pbrudny** [comment]
@sgoraczynski It's not obvious. Just think what the final stage should be.

In this case. You should just leave that 

`ctx.lineTo(xCoordinate, 120);`

and remove the rest

**Comment by sgoraczynski** [comment]
I mean, both are wrong

**Comment by sgoraczynski** [comment]
Ahaaa... okey, moment

**Comment by pbrudny** [comment]
sometimes you need to take 'good things' from both cases.
and add them to the final solution

**Comment by sgoraczynski** [comment]
Okey
But should I also delete those arrows and names of branches?

**Comment by pbrudny** [comment]
@sgoraczynski Yes. Of course. Just leave the proper code (or construct the proper one). No arrows or wrong code is needed.

**Comment by sgoraczynski** [comment]
Yes sir!

**Comment by sgoraczynski** [comment]
Thank You sir!

**Comment by pbrudny** [comment]
@sgoraczynski 

```
<<<<<<< refactor-3
            ctx.lineTo(132, 120);
=======
            ctx.lineTo(xCoordinate, 120);    								//Sides and upper helmet
>>>>>>> main
```

in this example first code has removed comment. Second one has the proper variable.
So you need to take 'the good' parts from both :)

**Comment by sgoraczynski** [comment]
Okey I got it

**Comment by sgoraczynski** [comment]
What if I've done it? What now?

**Comment by sgoraczynski** [comment]
Should I click "Commit merge"?
What if I made a mistake,?

**Comment by pbrudny** [comment]
yes. commit that... If you made a mistake...? Hm...Github will explode 💥

**Comment by pbrudny** [comment]
@sgoraczynski Don't worry about that... If you made a mistake we learn a lot while fixing it :D

**Comment by sgoraczynski** [comment]
Okey hahaha

**Pull request merged**
